/**
 * @file agent/prompt.ts
 * @description System prompt constructor assembling the 6 core context layers.
 * 
 * THE 6 PROMPT LAYERS:
 * 1. Identity & Operating Directives (Direct, senior engineer, inspect before editing).
 * 2. Environment Context (Workspace path, OS platform, current timestamp).
 * 3. Project Instructions (Loaded automatically from AGENTS.md or CLAUDE.md in workspace root).
 * 4. Codebase Directory Map (Compact ASCII file tree generated by repomap scanner).
 * 5. Active Integrations (Web Search, GitHub, Linear, Sentry, Slack, MCP — only if enabled).
 * 6. Tool Calling Protocol (JSON guidelines + XML tag definitions fallback).
 */

import * as fs from 'fs/promises';
import * as path from 'path';
import * as os from 'os';
import { generateWorkspaceTree } from '../repomap/scanner';
import { CORE_TOOL_XML_DEFINITIONS } from '../tools/registry';

export interface PromptContextOptions {
  workspaceRoot: string;
  activeIntegrations?: string[];
  customInstructions?: string;
}

/**
 * Attempts to load project-specific instruction files (`AGENTS.md` or `CLAUDE.md`) from workspace root.
 */
async function loadProjectInstructions(workspaceRoot: string): Promise<string | null> {
  const candidates = ['AGENTS.md', 'agents.md', 'CLAUDE.md', 'claude.md'];

  for (const filename of candidates) {
    try {
      const fullPath = path.join(workspaceRoot, filename);
      const content = await fs.readFile(fullPath, 'utf-8');
      if (content.trim()) {
        return `[Project Instructions from ${filename}]\n${content.trim()}`;
      }
    } catch {
      // File does not exist, check next candidate
    }
  }

  return null;
}

/**
 * Constructs the complete, production-grade system prompt for an agent session.
 * 
 * @param options Configuration options including workspaceRoot and active integrations.
 * @returns Promise<string> Complete formatted system prompt.
 */
export async function buildSystemPrompt(options: PromptContextOptions): Promise<string> {
  const { workspaceRoot, activeIntegrations, customInstructions } = options;

  // 1. Load project instructions (AGENTS.md / CLAUDE.md)
  const projectInstructions = await loadProjectInstructions(workspaceRoot);

  // 2. Generate compact workspace file tree
  const workspaceTree = await generateWorkspaceTree(workspaceRoot);

  // 3. Detect operating environment
  const platform = os.platform(); // 'darwin' | 'linux' | 'win32'
  const osName = platform === 'darwin' ? 'macOS' : platform === 'win32' ? 'Windows' : 'Linux';
  const currentDate = new Date().toISOString().split('T')[0];

  // 4. Assemble the prompt sections
  const sections: string[] = [];

  // LAYER 1: IDENTITY & GUIDELINES
  sections.push(`You are Unfuse, a local AI coding assistant running directly on the user's machine.
You help the user write, debug, refactor, and navigate code in their workspace.

GUIDELINES:
- Be direct and concise. Avoid conversational filler, preambles, or repeating the user's request.
- Inspect files with 'read' before editing. Never guess line numbers or file contents.
- Match the codebase's existing code style, indentation, and conventions.
- Use 'bash' to run tests, type checks, or search files rather than speculating.
- For long-running commands (dev servers, watchers), use 'background: true'.`);

  // LAYER 2: ENVIRONMENT
  sections.push(`ENVIRONMENT:
- Workspace Root: ${workspaceRoot}
- Operating System: ${osName} (${platform})
- Date: ${currentDate}`);

  // LAYER 3: PROJECT CONVENTIONS (AGENTS.md / CLAUDE.md)
  if (projectInstructions) {
    sections.push(`PROJECT RULES & CONVENTIONS:\n${projectInstructions}`);
  }

  // LAYER 4: WORKSPACE REPOSITORY MAP
  sections.push(`WORKSPACE FILE STRUCTURE:\n${workspaceTree}`);

  // LAYER 5: ACTIVE INTEGRATIONS (if any)
  if (activeIntegrations && activeIntegrations.length > 0) {
    const integrationsText = activeIntegrations.map((item) => `- ${item}`).join('\n');
    sections.push(`ACTIVE INTEGRATIONS & SERVICES:\n${integrationsText}`);
  }

  // LAYER 6: TOOL CALLING PROTOCOL (JSON + XML FALLBACK)
  sections.push(`TOOL INVOCATION PROTOCOL:
You have access to 4 core tools: 'read', 'write', 'edit', and 'bash'.
If calling tools natively via JSON, use standard function calling.
If emitting tool calls as text tags, use the following XML format:

<tool_call>
{"name": "read", "arguments": {"path": "src/App.tsx", "startLine": 1, "endLine": 50}}
</tool_call>

TOOL SPECIFICATIONS:
${CORE_TOOL_XML_DEFINITIONS}`);

  // Custom session overrides
  if (customInstructions) {
    sections.push(`USER SESSION INSTRUCTIONS:\n${customInstructions}`);
  }

  return sections.join('\n\n---\n\n');
}
